[package]
edition = "2021"
name = "slim-futures"
version = "0.1.0"

[dependencies]
futures-core = "0.3"
pin-project-lite = "0.2"

[dev-dependencies]
futures-util = "0.3"
tokio = { version = "1", features = ["macros", "rt"] }
