#![allow(clippy::module_name_repetitions)] // False positive, for `IntoTryFuture`,

pub use self::and_then::AndThen;
pub use self::and_then_async::AndThenAsync;
pub use self::err::{err_by, err_by_clone, err_by_copy, err_by_take, Err};
pub use self::err_into::ErrInto;
pub use self::flatten::Flatten;
pub use self::flatten_async_iterator::FlattenAsyncIterator;
pub use self::future_ext::FutureExt;
pub use self::inspect::Inspect;
pub use self::inspect_err::InspectErr;
pub use self::inspect_ok::InspectOk;
pub use self::into_result_future::IntoResultFuture;
pub use self::lazy::{lazy, Lazy};
pub use self::map::Map;
pub use self::map_async::MapAsync;
pub use self::map_err::MapErr;
pub use self::map_into::MapInto;
pub use self::map_ok::MapOk;
pub use self::map_ok_async::MapOkAsync;
pub use self::map_ok_or_else::MapOkOrElse;
pub use self::map_ok_or_else_async::MapOkOrElseAsync;
pub use self::ok::{ok_by, ok_by_clone, ok_by_copy, ok_by_take, Ok};
pub use self::ok_into::OkInto;
pub use self::or_else_async::OrElseAsync;
pub use self::raw_map_ok_or_else_async::RawMapOkOrElseAsync;
pub use self::raw_select::{raw_select, RawSelect};
pub use self::ready::{ready_by, ready_by_clone, ready_by_copy, ready_by_take, Ready};
pub use self::select_either::{select_either, SelectEither};
pub use self::try_flatten::TryFlatten;
pub use self::try_flatten_err::TryFlattenErr;
pub use self::try_select_either::{try_select_either, TrySelectEither};
pub use self::unwrap_or_else::UnwrapOrElse;
pub use self::unwrap_or_else_async::UnwrapOrElseAsync;

mod and_then;
mod and_then_async;
mod err;
mod err_into;
mod flatten;
mod flatten_async_iterator;
mod future_ext;
mod inspect;
mod inspect_err;
mod inspect_ok;
mod into_result_future;
mod lazy;
mod map;
mod map_async;
mod map_err;
mod map_err_async;
mod map_into;
mod map_ok;
mod map_ok_async;
mod map_ok_or_else;
mod map_ok_or_else_async;
mod ok;
mod ok_into;
mod or_else;
mod or_else_async;
mod raw_map_ok_or_else_async;
mod raw_select;
mod ready;
mod select_either;
mod try_flatten;
mod try_flatten_err;
mod try_select_either;
mod unwrap_or_else;
mod unwrap_or_else_async;
