pub use crate::and_then::AndThen;
pub use crate::flatten::Flatten;
pub use crate::future_ext::FutureExt as SlimFutureExt;
pub use crate::inspect::Inspect;
pub use crate::lazy::{lazy, Lazy};
pub use crate::map::Map;
pub use crate::map_async::MapAsync;
pub use crate::map_into::MapInto;
pub use crate::map_ok::MapOk;
pub use crate::ready::{ready, Ready};
pub use crate::select::Select;
pub use crate::try_flatten::TryFlatten;

mod and_then;
mod assert_future;
mod flatten;
mod fn_mut_1;
mod future_ext;
mod inspect;
mod lazy;
mod map;
mod map_async;
mod map_into;
mod map_ok;
mod ready;
mod select;
mod try_flatten;
